### ISSUE TITLE
Change data to match format in pbf-analysis

### ISSUE THREAD

**Issue by machow** [CodeForPhilly/pbf-scraping#8]
* modify scrape.py and parse.py to generate / use data matching this data dictionary in pbf-analysis. No need for id column, and it sounds like parse.py will need the original names in the data.

[pbf-analysis data](https://github.com/CodeForPhilly/pbf-analysis/blob/master/Data/0c_distinct_dockets.csv)

[data dictionary](https://github.com/CodeForPhilly/pbf-analysis/blob/master/Data/data_dictionary.csv)

I think the main thing is cleaning column names to be lowercase and use underscores. The big benefit is that it would let them create graphs etc.. that could be put into the email (e.g. as part of a weekly summary)!

I wonder if someone working on an analysis right now might want to take this up?

**Comment by machow** [comment]
## TODO

- [ ] : load earlier data from pbf-analysis into athena
- [ ] : data between pbf-analysis and now that Adam sent
- [ ] : analysis script, count of charges per day
- [ ] : reconciling issue described (how would they access data, rules for submitting and reviewing PR, etc..)

## Acceptance criteria

* All data reconciled, meaning you generate count of charges per day going back to earliest date collected in pbf-analysis
* No gaps in data (or gaps explicitly documented)
